[package]
name = "cloud-wand-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }

cloud-wand-parser = { path = "../parser" }
